wandb_version: 1

gym_id:
  desc: null
  value: PBDroneEnv
env:
  desc: null
  value: default
env_config:
  desc: null
  value: default
env_kwargs:
  desc: null
  value: '{}'
log_dir:
  desc: null
  value: logs
exp_name:
  desc: null
  value: test
seed:
  desc: null
  value: 1
cuda:
  desc: null
  value: false
gui:
  desc: null
  value: true
save_buffer:
  desc: null
  value: false
save_model:
  desc: null
  value: true
save_obs:
  desc: null
  value: false
save_video:
  desc: null
  value: false
save_dir:
  desc: null
  value: ''
checkpoint_freq:
  desc: null
  value: 100
checkpoint_at_end:
  desc: null
  value: false
restore_agent:
  desc: null
  value: false
num_cpus:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 0
num_envs:
  desc: null
  value: 1
max_steps:
  desc: null
  value: 5000000.0
agent:
  desc: null
  value: PPO
agent_config:
  desc: null
  value: default
policy:
  desc: null
  value: default
policy_config:
  desc: null
  value: default
discount:
  desc: null
  value: 0.999
threshold:
  desc: null
  value: 0.3
batch_size:
  desc: null
  value: 2048
num_steps:
  desc: null
  value: 2048
eval_criterion:
  desc: null
  value: default
eval_criterion_config:
  desc: null
  value: default
metric:
  desc: null
  value: default
metric_config:
  desc: null
  value: default
optimizer:
  desc: null
  value: default
optimizer_config:
  desc: null
  value: default
criterion:
  desc: null
  value: default
criterion_config:
  desc: null
  value: default
wandb_project_name:
  desc: null
  value: ppo-implementation-details
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/Sol/Model/pybullet_drone_simulator.py
    python_version: 3.8.18
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704230603.839752
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 1
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.8.18
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''net_arch'': [256, 256, 256], ''activation_fn'': <class ''torch.nn.modules.activation.GELU''>}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 5000000
_num_timesteps_at_start:
  desc: null
  value: 0
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1704230652957748600
learning_rate:
  desc: null
  value: 0.001
tensorboard_log:
  desc: null
  value: ./logs/ppo_tensorboard/
_last_obs:
  desc: null
  value: "[[ 0.          0.          0.00022793  0.         -0.          0.\n   0.\
    \          0.          0.          0.          0.          0.        ]\n [ 0.\
    \          0.          0.00022793  0.         -0.          0.\n   0.         \
    \ 0.          0.          0.          0.          0.        ]\n [ 0.         \
    \ 0.          0.00022793  0.         -0.          0.\n   0.          0.      \
    \    0.          0.          0.          0.        ]\n [ 0.          0.      \
    \    0.00022793  0.         -0.          0.\n   0.          0.          0.   \
    \       0.          0.          0.        ]\n [ 0.          0.          0.00022793\
    \  0.         -0.          0.\n   0.          0.          0.          0.     \
    \     0.          0.        ]\n [ 0.          0.          0.00022793  0.     \
    \    -0.          0.\n   0.          0.          0.          0.          0.  \
    \        0.        ]\n [ 0.          0.          0.00022793  0.         -0.  \
    \        0.\n   0.          0.          0.          0.          0.          0.\
    \        ]\n [ 0.          0.          0.00022793  0.         -0.          0.\n\
    \   0.          0.          0.          0.          0.          0.        ]\n\
    \ [ 0.          0.          0.00022793  0.         -0.          0.\n   0.    \
    \      0.          0.          0.          0.          0.        ]\n [ 0.    \
    \      0.          0.00022793  0.         -0.          0.\n   0.          0. \
    \         0.          0.          0.          0.        ]\n [ 0.          0. \
    \         0.00022793  0.         -0.          0.\n   0.          0.          0.\
    \          0.          0.          0.        ]\n [ 0.          0.          0.00022793\
    \  0.         -0.          0.\n   0.          0.          0.          0.     \
    \     0.          0.        ]\n [ 0.          0.          0.00022793  0.     \
    \    -0.          0.\n   0.          0.          0.          0.          0.  \
    \        0.        ]\n [ 0.          0.          0.00022793  0.         -0.  \
    \        0.\n   0.          0.          0.          0.          0.          0.\
    \        ]\n [ 0.          0.          0.00022793  0.         -0.          0.\n\
    \   0.          0.          0.          0.          0.          0.        ]\n\
    \ [ 0.          0.          0.00022793  0.         -0.          0.\n   0.    \
    \      0.          0.          0.          0.          0.        ]\n [ 0.    \
    \      0.          0.00022793  0.         -0.          0.\n   0.          0. \
    \         0.          0.          0.          0.        ]\n [ 0.          0. \
    \         0.00022793  0.         -0.          0.\n   0.          0.          0.\
    \          0.          0.          0.        ]\n [ 0.          0.          0.00022793\
    \  0.         -0.          0.\n   0.          0.          0.          0.     \
    \     0.          0.        ]\n [ 0.          0.          0.00022793  0.     \
    \    -0.          0.\n   0.          0.          0.          0.          0.  \
    \        0.        ]\n [ 0.          0.          0.00022793  0.         -0.  \
    \        0.\n   0.          0.          0.          0.          0.          0.\
    \        ]\n [ 0.          0.          0.00022793  0.         -0.          0.\n\
    \   0.          0.          0.          0.          0.          0.        ]\n\
    \ [ 0.          0.          0.00022793  0.         -0.          0.\n   0.    \
    \      0.          0.          0.          0.          0.        ]\n [ 0.    \
    \      0.          0.00022793  0.         -0.          0.\n   0.          0. \
    \         0.          0.          0.          0.        ]]"
_last_episode_starts:
  desc: null
  value: "[ True  True  True  True  True  True  True  True  True  True  True  True\n\
    \  True  True  True  True  True  True  True  True  True  True  True  True]"
_last_original_obs:
  desc: null
  value: "[[ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n\
    \   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.   \
    \   0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125\
    \  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [\
    \ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.  \
    \    0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.  \
    \    0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.   \
    \  -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.    \
    \  0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0. \
    \     0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0. \
    \     0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.  \
    \    0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.   \
    \   0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.\
    \    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n\
    \   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.   \
    \   0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125\
    \  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [\
    \ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.  \
    \    0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.  \
    \    0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.   \
    \  -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.    \
    \  0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0. \
    \     0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0. \
    \     0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.  \
    \    0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.   \
    \   0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.\
    \    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n\
    \   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.   \
    \   0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125\
    \  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [\
    \ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.  \
    \    0.      0.    ]]"
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
_vec_normalize_env:
  desc: null
  value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x000001EB38DD3580>
observation_space:
  desc: null
  value: Box([-2. -2.  0. -1. -1. -1. -1. -1. -1. -1. -1. -1.], [2. 2. 2. 1. 1. 1.
    1. 1. 1. 1. 1. 1.], (12,), float64)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (4,), float64)
n_envs:
  desc: null
  value: 24
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.01
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x000001EB42ED3D30>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x000001EB42DF9F70>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001EB42EA65E0>
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x000001EB4DB76CD0>
