wandb_version: 1

gym_id:
  desc: null
  value: PBDroneEnv
env:
  desc: null
  value: default
env_config:
  desc: null
  value: default
env_kwargs:
  desc: null
  value: '{}'
log_dir:
  desc: null
  value: logs
seed:
  desc: null
  value: 1
cuda:
  desc: null
  value: true
gui:
  desc: null
  value: true
save_buffer:
  desc: null
  value: false
save_model:
  desc: null
  value: true
save_dir:
  desc: null
  value: ''
checkpoint_freq:
  desc: null
  value: 100
restore_agent:
  desc: null
  value: false
vec_check_nan:
  desc: null
  value: false
vec_normalize:
  desc: null
  value: false
ve_check_env:
  desc: null
  value: false
num_cpus:
  desc: null
  value: 1
max_steps:
  desc: null
  value: 5000000.0
agent:
  desc: null
  value: PPO
agent_config:
  desc: null
  value: default
policy:
  desc: null
  value: default
policy_config:
  desc: null
  value: default
discount:
  desc: null
  value: 0.999
threshold:
  desc: null
  value: 0.3
batch_size:
  desc: null
  value: 2048
num_steps:
  desc: null
  value: 2048
learning_rate:
  desc: null
  value: 0.001
clip_range:
  desc: null
  value: 0.2
ent_coef:
  desc: null
  value: 0
eval_criterion:
  desc: null
  value: default
eval_criterion_config:
  desc: null
  value: default
metric:
  desc: null
  value: default
metric_config:
  desc: null
  value: default
optimizer:
  desc: null
  value: default
optimizer_config:
  desc: null
  value: default
criterion:
  desc: null
  value: default
criterion_config:
  desc: null
  value: default
wandb:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: false
output_folder:
  desc: null
  value: results
_wandb:
  desc: null
  value:
    code_path: code/Sol/Model/simulation_controller.py
    python_version: 3.8.18
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704390218.066942
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 1
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.8.18
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''activation_fn'': <class ''torch.nn.modules.activation.Tanh''>, ''net_arch'':
    {''vf'': [512, 512, 256, 128], ''pi'': [512, 512, 256, 128]}}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 5000000
_num_timesteps_at_start:
  desc: null
  value: 0
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1704390263654181500
tensorboard_log:
  desc: null
  value: ./logs/ppo_tensorboard/
_last_obs:
  desc: null
  value: "[[ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n\
    \   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.   \
    \   0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125\
    \  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [\
    \ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.  \
    \    0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.  \
    \    0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.   \
    \  -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.    \
    \  0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0. \
    \     0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0. \
    \     0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.  \
    \    0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.   \
    \   0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.\
    \    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n\
    \   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.   \
    \   0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125\
    \  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [\
    \ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.  \
    \    0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.  \
    \    0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.   \
    \  -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.    \
    \  0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0. \
    \     0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0. \
    \     0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.  \
    \    0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.   \
    \   0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.\
    \    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n\
    \   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.   \
    \   0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125\
    \  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [\
    \ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.  \
    \    0.      0.    ]]"
_last_episode_starts:
  desc: null
  value: "[ True  True  True  True  True  True  True  True  True  True  True  True\n\
    \  True  True  True  True  True  True  True  True  True  True  True  True]"
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box([-2. -2.  0. -1. -1. -1. -1. -1. -1. -1. -1. -1.], [2. 2. 2. 1. 1. 1.
    1. 1. 1. 1. 1. 1.], (12,), float64)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (4,), float64)
n_envs:
  desc: null
  value: 24
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
n_epochs:
  desc: null
  value: 10
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x000001E4C3789940>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001E4C35D53D0>
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x000001E4CE41B610>
