wandb_version: 1

gym_id:
  desc: null
  value: PBDroneEnv
env:
  desc: null
  value: default
env_config:
  desc: null
  value: default
env_kwargs:
  desc: null
  value: '{}'
log_dir:
  desc: null
  value: logs
seed:
  desc: null
  value: 1
cuda:
  desc: null
  value: true
gui:
  desc: null
  value: true
save_run:
  desc: null
  value: true
save_buffer:
  desc: null
  value: false
save_model:
  desc: null
  value: true
save_dir:
  desc: null
  value: ''
checkpoint_freq:
  desc: null
  value: 100
restore_agent:
  desc: null
  value: false
vec_check_nan:
  desc: null
  value: false
vec_normalize:
  desc: null
  value: false
ve_check_env:
  desc: null
  value: false
num_cpus:
  desc: null
  value: 1
max_steps:
  desc: null
  value: 5000000.0
agent:
  desc: null
  value: SAC
agent_config:
  desc: null
  value: default
discount:
  desc: null
  value: 0.999
threshold:
  desc: null
  value: 0.3
batch_size:
  desc: null
  value: 2048
num_steps:
  desc: null
  value: 2048
learning_rate:
  desc: null
  value: 0.001
clip_range:
  desc: null
  value: 0.2
ent_coef:
  desc: null
  value: 0
eval_criterion:
  desc: null
  value: default
eval_criterion_config:
  desc: null
  value: default
metric:
  desc: null
  value: default
metric_config:
  desc: null
  value: default
optimizer:
  desc: null
  value: default
optimizer_config:
  desc: null
  value: default
criterion:
  desc: null
  value: default
criterion_config:
  desc: null
  value: default
wandb:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: false
output_folder:
  desc: null
  value: results
_wandb:
  desc: null
  value:
    code_path: code/Sol/Model/simulation_controller.py
    python_version: 3.8.18
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704467326.94336
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 1
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.8.18
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.SACPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 0
policy_kwargs:
  desc: null
  value: '{''activation_fn'': <class ''torch.nn.modules.activation.ReLU''>, ''net_arch'':
    [512, 512, 256, 128], ''use_sde'': False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 5000000
_num_timesteps_at_start:
  desc: null
  value: 0
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1704467370942356500
tensorboard_log:
  desc: null
  value: ./logs/SAC_tensorboard/
_last_obs:
  desc: null
  value: "[[ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n\
    \   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.   \
    \   0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125\
    \  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [\
    \ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.  \
    \    0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.  \
    \    0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.   \
    \  -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.    \
    \  0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0. \
    \     0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0. \
    \     0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.  \
    \    0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.   \
    \   0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.\
    \    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n\
    \   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.   \
    \   0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125\
    \  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [\
    \ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.  \
    \    0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.  \
    \    0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.   \
    \  -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.    \
    \  0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0. \
    \     0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0. \
    \     0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.  \
    \    0.      0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.   \
    \   0.1125  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.\
    \    ]\n [ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n\
    \   0.      0.      0.    ]\n [ 0.      0.      0.1125  0.     -0.      0.   \
    \   0.      0.      0.\n   0.      0.      0.    ]\n [ 0.      0.      0.1125\
    \  0.     -0.      0.      0.      0.      0.\n   0.      0.      0.    ]\n [\
    \ 0.      0.      0.1125  0.     -0.      0.      0.      0.      0.\n   0.  \
    \    0.      0.    ]]"
_last_episode_starts:
  desc: null
  value: "[ True  True  True  True  True  True  True  True  True  True  True  True\n\
    \  True  True  True  True  True  True  True  True  True  True  True  True]"
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box([-2. -2.  0. -1. -1. -1. -1. -1. -1. -1. -1. -1.], [2. 2. 2. 1. 1. 1.
    1. 1. 1. 1. 1. 1.], (12,), float64)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (4,), float64)
n_envs:
  desc: null
  value: 24
buffer_size:
  desc: null
  value: 4000000
learning_starts:
  desc: null
  value: 100
tau:
  desc: null
  value: 0.005
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 2
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x0000017F6034CD00>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -4.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x0000017F6AA551F0>
policy:
  desc: null
  value: "SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n\
    \      (0): Linear(in_features=12, out_features=512, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=512, out_features=512, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=512, out_features=256, bias=True)\n      (5): ReLU()\n\
    \      (6): Linear(in_features=256, out_features=128, bias=True)\n      (7): ReLU()\n\
    \    )\n    (mu): Linear(in_features=128, out_features=4, bias=True)\n    (log_std):\
    \ Linear(in_features=128, out_features=4, bias=True)\n  )\n  (critic): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=16,\
    \ out_features=512, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=512,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=16,\
    \ out_features=512, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=512,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=16,\
    \ out_features=512, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=512,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=16,\
    \ out_features=512, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=512,\
    \ out_features=256, bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n    )\n  )\n)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=12,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n  )\n  (mu): Linear(in_features=128,\
    \ out_features=4, bias=True)\n  (log_std): Linear(in_features=128, out_features=4,\
    \ bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=16,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=16,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=16,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=16,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=256, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=256,\
    \ out_features=128, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=128,\
    \ out_features=1, bias=True)\n  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x0000017F7B260FA0>
