wandb_version: 1

gym_id:
  desc: null
  value: PBDroneEnv
env:
  desc: null
  value: default
env_config:
  desc: null
  value: default
env_kwargs:
  desc: null
  value: '{}'
log_dir:
  desc: null
  value: logs
exp_name:
  desc: null
  value: test
seed:
  desc: null
  value: 1
cuda:
  desc: null
  value: false
gui:
  desc: null
  value: true
save_buffer:
  desc: null
  value: false
save_model:
  desc: null
  value: true
save_obs:
  desc: null
  value: false
save_video:
  desc: null
  value: false
save_dir:
  desc: null
  value: ''
checkpoint_freq:
  desc: null
  value: 100
checkpoint_at_end:
  desc: null
  value: false
restore_agent:
  desc: null
  value: false
restore_buffer:
  desc: null
  value: false
restore_optimizer:
  desc: null
  value: false
restore:
  desc: null
  value: null
num_cpus:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 0
num_envs:
  desc: null
  value: 1
num_steps:
  desc: null
  value: 5000000.0
agent:
  desc: null
  value: PPO
agent_config:
  desc: null
  value: default
policy:
  desc: null
  value: default
policy_config:
  desc: null
  value: default
eval_criterion:
  desc: null
  value: default
eval_criterion_config:
  desc: null
  value: default
metric:
  desc: null
  value: default
metric_config:
  desc: null
  value: default
optimizer:
  desc: null
  value: default
optimizer_config:
  desc: null
  value: default
criterion:
  desc: null
  value: default
criterion_config:
  desc: null
  value: default
wandb_project_name:
  desc: null
  value: ppo-implementation-details
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/Sol/Model/pybullet_drone_simulator.py
    python_version: 3.8.18
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704204704.317518
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.8.18
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
