wandb_version: 1

exp_name:
  desc: null
  value: pybullet_drone_simulator
gym_id:
  desc: null
  value: PBDroneEnv
run_type:
  desc: null
  value: full
env_config:
  desc: null
  value: default
env_kwargs:
  desc: null
  value: '{}'
seed:
  desc: null
  value: 1
cuda:
  desc: null
  value: true
gui:
  desc: null
  value: false
savemodel:
  desc: null
  value: true
logdir:
  desc: null
  value: logs
savedir:
  desc: null
  value: ''
checkpoint_freq:
  desc: null
  value: 100
vec_check_nan:
  desc: null
  value: false
vec_normalize:
  desc: null
  value: false
ve_check_env:
  desc: null
  value: false
num_envs:
  desc: null
  value: 1
max_steps:
  desc: null
  value: 10e6
max_env_steps:
  desc: null
  value: 5000
learning_rate:
  desc: null
  value: 0.001
agent:
  desc: null
  value: PPO
agent_config:
  desc: null
  value: default
discount:
  desc: null
  value: 0.999
threshold:
  desc: null
  value: 0.3
batch_size:
  desc: null
  value: 40960
num_steps:
  desc: null
  value: 2048
clip_range:
  desc: null
  value: 0.2
ent_coef:
  desc: null
  value: 0
eval_criterion:
  desc: null
  value: default
eval_criterion_config:
  desc: null
  value: default
metric:
  desc: null
  value: default
metric_config:
  desc: null
  value: default
optimizer:
  desc: null
  value: default
optimizer_config:
  desc: null
  value: default
criterion:
  desc: null
  value: default
criterion_config:
  desc: null
  value: default
wandb:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: null
wandb_rootlog:
  desc: null
  value: /wandb
capture_video:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/Sol/Model/pybullet_drone_simulator.py
    python_version: 3.8.18
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704893251.152289
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.8.18
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
